### ISSUE TITLE
software fails to compile with OSX 10.9 (Mavericks)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Oshlack/Corset#5]
```
What steps will reproduce the problem?
1. ./configure --with-bam_inc=/usr/local/include/bam/
2. make
3.

What is the expected output? What do you see instead?
g++ -I/usr/local/include/bam/ -O3 -ffast-math -I./   -std=c++0x -DUNORDEREDMAP 
-c corset.cc -o corset.o -DVERSION=1.00
corset.cc:83:14: warning: unsequenced modification and access to 'in' 
[-Wunsequenced]
     if ((in = samopen(filename.c_str(), "br", NULL)) == 0 | in->header == 0) {
             ^                                               ~~
corset.cc:328:11: warning: & has lower precedence than !=; != will be evaluated 
first [-Wparentheses]
        if(force & remove( filename.c_str() )!=0){
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
corset.cc:328:11: note: place parentheses around the '!=' expression to silence 
this warning
        if(force & remove( filename.c_str() )!=0){
                 ^
                   (                            )
corset.cc:328:11: note: place parentheses around the & expression to evaluate 
it first
        if(force & remove( filename.c_str() )!=0){
                 ^
           (             )
corset.cc:356:28: error: variable length array of non-POD element type 
'read_bam_args' (aka 'read_bam_arguments')
  read_bam_args thread_args[smpls];
                           ^
2 warnings and 1 error generated.
make: *** [corset.o] Error 1

What version of the product are you using? On what operating system?
1.00 on OSX 10.9.4

Please provide any additional information below.
Time to fire up VirtualBox I guess.

```

Original issue reported on code.google.com by `heath.ob...@gmail.com` on 29 Jul 2014 at 2:47
